displayName=Floating Examine Text
author=dillinger93
description=Shows examine text directly on target
tags=quality of life,qol,examine,chat,popup
plugins=com.example.ExamplePlugin
id=floatingexaminetext
version=1.0.0
